package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/exec"
	"runtime"
	"strconv"
	"strings"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
	"github.com/sudorandom/protodocs"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

func openBrowser(url string) {
	var err error
	switch runtime.GOOS {
	case "linux":
		err = exec.Command("xdg-open", url).Start()
	case "windows":
		err = exec.Command("rundll32", "url.dll,FileProtocolHandler", url).Start()
	case "darwin":
		err = exec.Command("open", url).Start()
	default:
		err = fmt.Errorf("unsupported platform: %s", runtime.GOOS)
	}
	if err != nil {
		log.Printf("Failed to open browser automatically: %v", err)
	}
}

func main() {
	pflag.String("addr", "127.0.0.1:8080", "Host:Port to listen on (port will auto-increment if taken)")
	pflag.String("static-dir", "", "Local path to static assets (overrides embedded files)")
	pflag.String("reflection-url", "", "Default gRPC/Connect Server Reflection URL")
	pflag.String("loading-method", "", "Default loading method ('http', 'grpc-web', 'connect')")
	pflag.String("default-tab", "", "Default tab to focus in the sidebar ('files' or 'services')")
	pflag.StringArray("bsr", nil, "Buf Schema Registry module to load (host/owner/repository[:ref])")
	pflag.String("bsr-token", "", "Buf Schema Registry API token (defaults to BUF_TOKEN)")
	pflag.Bool("bsr-source-info", true, "Request source information from the Buf Schema Registry")
	pflag.Bool("open", true, "Automatically open ProtoDocs in the browser")
	pflag.Parse()

	_ = viper.BindPFlags(pflag.CommandLine)
	viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))
	viper.AutomaticEnv()

	addr := viper.GetString("addr")
	staticDir := viper.GetString("static-dir")
	reflectionURL := viper.GetString("reflection-url")
	loadingMethod := viper.GetString("loading-method")
	defaultTab := viper.GetString("default-tab")
	bsrToken := viper.GetString("bsr-token")
	bsrSourceInfo := viper.GetBool("bsr-source-info")
	autoOpen := viper.GetBool("open")

	descriptorFiles := pflag.Args()
	bsrModules, err := pflag.CommandLine.GetStringArray("bsr")
	if err != nil {
		log.Fatalf("Failed to read BSR module flags: %v", err)
	}

	// Build configuration
	cfg := protodocs.Config{
		Title:             "ProtoDocs",
		LogoText:          "ProtoDocs",
		LoadingMethod:     loadingMethod,
		LocalPath:         staticDir,
		Proxy:             true,
		ProxyAllowedHosts: []string{"*"},
		DefaultTab:        defaultTab,
		FrontPageSections: []protodocs.FrontPageSection{
			{
				Type: "markdown",
				Markdown: `# ProtoDocs

Browse the loaded protobuf descriptors as linked reference documentation. Use the sidebar to jump by file or service, inspect messages and enums, and try supported RPCs directly from the service pages.`,
			},
			{Type: "descriptor-stats-panel"},
			{Type: "service-list-panel"},
			{
				Type:     "markdown-small",
				Markdown: `Generated by ` + "`protodocs`" + `.`,
			},
		},
	}

	if reflectionURL != "" {
		cfg.ReflectionURL = reflectionURL
		cfg.ServerURL = reflectionURL
	}

	if cfg.LoadingMethod == "" {
		if reflectionURL != "" {
			cfg.LoadingMethod = "connect"
		} else {
			cfg.LoadingMethod = "http"
		}
	}

	// Load positional descriptor files from disk into memory
	if len(descriptorFiles) > 0 {
		mergedSet := &descriptorpb.FileDescriptorSet{}
		for _, path := range descriptorFiles {
			bytes, err := os.ReadFile(path)
			if err != nil {
				log.Fatalf("Failed to read descriptor file %s: %v", path, err)
			}
			var fds descriptorpb.FileDescriptorSet
			if err := proto.Unmarshal(bytes, &fds); err != nil {
				log.Fatalf("Failed to parse descriptor file %s: %v", path, err)
			}
			mergedSet.File = append(mergedSet.File, fds.File...)
		}
		cfg.Descriptors = mergedSet
	}

	if len(bsrModules) > 0 {
		modules := make([]protodocs.BSRModule, 0, len(bsrModules))
		for _, moduleRef := range bsrModules {
			moduleRef = strings.TrimSpace(moduleRef)
			if moduleRef == "" {
				continue
			}
			modules = append(modules, protodocs.BSRModule{
				Module:     moduleRef,
				SourceInfo: bsrSourceInfo,
			})
		}
		if len(modules) > 0 {
			if bsrToken == "" {
				bsrToken = os.Getenv("BUF_TOKEN")
			}
			bsrSet, err := protodocs.FetchBSRDescriptors(context.Background(), nil, modules, bsrToken)
			if err != nil {
				log.Fatalf("Failed to load BSR descriptors: %v", err)
			}
			if cfg.Descriptors == nil {
				cfg.Descriptors = &descriptorpb.FileDescriptorSet{}
			}
			cfg.Descriptors.File = append(cfg.Descriptors.File, bsrSet.File...)
		}
	}

	// If nothing was supplied, configure the default descriptor files.
	if len(descriptorFiles) == 0 && len(bsrModules) == 0 && reflectionURL == "" {
		cfg.DescriptorFiles = []string{
			"/eliza.binpb",
			"/googleapis.binpb",
			"/protovalidate.binpb",
			"/wellknowntypes.binpb",
			"/config.binpb",
		}
	}

	handler, err := protodocs.NewHandler(cfg)
	if err != nil {
		log.Fatalf("Failed to initialize ProtoDocs handler: %v", err)
	}

	// Auto-port allocation
	host, portStr, err := net.SplitHostPort(addr)
	if err != nil {
		log.Fatalf("Invalid addr %q: %v", addr, err)
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		log.Fatalf("Invalid port in addr %q: %v", addr, err)
	}

	var listener net.Listener
	for i := 0; i <= 100; i++ {
		currentPort := port + i
		tryAddr := fmt.Sprintf("%s:%d", host, currentPort)
		listener, err = net.Listen("tcp", tryAddr)
		if err == nil {
			port = currentPort
			break
		}
	}
	if err != nil {
		log.Fatalf("Could not bind to any TCP port starting from %d: %v", port, err)
	}

	displayHost := host
	if displayHost == "0.0.0.0" || displayHost == "" {
		displayHost = "localhost"
	}
	serverURL := fmt.Sprintf("http://%s:%d", displayHost, port)
	log.Printf("ProtoDocs CLI running on: %s", serverURL)

	if autoOpen {
		go func() {
			openBrowser(serverURL)
		}()
	}

	server := &http.Server{
		Addr:    listener.Addr().String(),
		Handler: handler,
	}
	err = server.Serve(listener)
	if err != nil && err != http.ErrServerClosed {
		log.Fatalf("HTTP server failed: %v", err)
	}
}
