// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialFile():Promise<string>;

export function GetProxyUrl():Promise<string>;

export function HandleFileOpen(arg1:string):Promise<void>;

export function ReadFileBytes(arg1:string):Promise<Array<number>>;
