// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function GetProxyUrl() {
  return window['go']['main']['App']['GetProxyUrl']();
}

export function HandleFileOpen(arg1) {
  return window['go']['main']['App']['HandleFileOpen'](arg1);
}

export function ReadFileBytes(arg1) {
  return window['go']['main']['App']['ReadFileBytes'](arg1);
}
